apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgA3Gd4Rk3D7m6z1xx/raPGBqRKcWQ8LSCKdlQZgxp+m5CPP42mOQh6J0pQnNYij1TJwhCA6I8FVDFWkboTBbcHJq4W9wZjBRle+8nNw4qDqy9mlFSfSlx1u8cRtKEW/0IBQTVPIohoQn8Wm364ALX6e0A84wSC3BrCYKMwRS6GQK12HbgtTj3j6BSI6aRwTp93jzh922H8BBbkM0Ai1u1j/79iT8HIygXMDRh7CCCK9pPJI66np5nvflpMcjdrzDIwRa0EuntOk53Pk0YCviUNKXoUdnHJioEd/9tIW56Dn1dNDf/6l2cvl1FdfAA5SAj8RBm0bMWl3Do2RUHtXl9nqbWsxrtvOP45KUZqd6IchbF7vwbsprEb8FR7FSEgIa9jZq71nBNGIu0QIIiKNfNQ3L12OrknoMhbZbf6RuARFyVhwt8ty+zocF6gud9h9LB1YF0a7mRUikUkRkPO9DkzNfOgeJG0DkqPUE0pvOC4Y1nb3TSLa6WpumoT0pIgfWT4nQnaUE28pVUrZyCCUo7OptHsaZkivy+XBDu2lN5cAQqIs1jiKkD4khsjls3ZOscdikkG0gq3xWX8rvQjUjKy1dxUnBOcwjoqHjGb96nXPoNUJMduiAC50KBJRnYmjrs9jOIIUoVZNP4d/LYr2fKHSAyDuTRxSzpPtyvMa7P1G/ubkOeYB9U1hBtN+pHhqzVsivsGPoT79BjA6MxLrtqllX+qsC1QSweuidFW3KvP8tArQ5xYk5g==
    ARTIFACTORY_PASSWORD: AgBTekB2GWemK0EoFlsfW9shKOZxjHmaEMEABvuYj9/YIl+q+aB8LGnFmOnjCEO2K/eQ+xpqOC9vEzGwrVWZ/Amjn29y/e3wASRgp9FZuoipaT10GJagnAJEj/Co5MexLV8KSzKJcpTcO5mi0U0l9TnCQ9qnytsxU8M7wHGZ6C+FF22YR+Bzr7SekzMp4/BzeRRHDWSSH2vI7Vpm9A+Hw/nkEDm632CkkSdMHMRDFjwYtxFFBL6wDBWfG57/bNFAzwG/ZPlG8ZUkYXcXrMNafhMqwcJQlGCOOks+WhFANaOdCC/nAwfYr7wQIcILCn8Eyw5twsycOwLx1LjhRbZo3EVRxlmIPpOjkkLVV1f4EietuDo4WNJaXpJznn3hjkRnZSiyfnUyllE39bWi0bRlZsae3XyJZHRjVpHRxHuC6+Pnl9COYkze7Dj9ZDaBN1Pe3LWHMfnfCeZ91ibYPpuv5j9OBWPB4R8cDDQ8ZXyaHTDK4ZH0BKBJfhqIs5g/MTvmf0lHYkoVQAYcsj1pbIplbu22ib5NqPWQ+o2wgqntarNmSMFHwZTCKPX67d6IfcjHVnDeL79njNWZT8czbbzmEcj099LYhOC6PbwshtYen8ypUNsTSRAcHKt1NrdfFq/O/VHfIJyEb+Ys5I2CkyVCK403ASG31YkqRDkzw4NnfE9Jv+s9hchG8Rw6FzChJM47JGRV2KVayNTTVAok9Q7VUc6Y6iLxyA==
    ARTIFACTORY_URL: AgBSFRCfxRj/S5Vm8Od07XG3UL4BkwdNUE55xgeTUjTf1XY+HooARS+VbTDqIhEL003CtGVZ+pUqBcBMSIFStSNkPvGnfVXnTrhcAYbmcTA/zOntdq9wJrwxAW82J9d2/iC9h9HcWBnVyk1uk7+6FblI2KRM8CTD6nwI+beYD3qN2qAGXiR0HBl83K+5Ln5jiMG2MDPiIVRnnCi504axPeT+31eiW/vW6UgNcsIGh3FsyJoHh+Mentk9Y6FzVz0XvBwodeunSxk+CVwImeCHz154bGkBHDrXaxevAv8VxstTue7riqJW+/FfakJEWMkOLE4GtQXsOQ30aIGzAwHDT54PeT3M/Ohj/KkTi1dwSZsMELLbCXGNYrLg/RADJnEds01rkkale2natKW3U2ZX1WXn0PAP+jQYzjHplzGS81mnDCUituJNqzoYw5eom/zLgVkpuQSprqCBoo1fdERG9mrPptqWDbZ51YhJXl7x+MA0HM+IPL5eA0YU8phjlCxVMz4456KjEzQ0taE1M55QQAi/FqvRQ4F77Wnni2+d7TkcDrD+f6wifn/MvHQz9/iQUhn11AoSgxy5xJqD/7h6M5czi+cnz54tqHtGyfNgenyyfm39BKsMfDhh3jqHBF7NUEJV39ofzleL8lRR1SfQfPfOCO3Au7CEqwhFk6332u60TI72DAW09Q0YOAdvY9Z1mAVksoVQG0RQWkSA+3OhQIDxIXVEkwc6pQvXHFj2eItIL1sq+ZqPZUYehg==
    ARTIFACTORY_USER: AgCsmiyvsx7rVRqI5XQjybW0jMfXIAWM8VVKXvpuXqQ6TsNUKGEpsmY7xaPY4Qa7VlU6Dm7O+pplThDBA994/kxRb5RfBATZYqF97EBCYm/J2JIyT0Z+FbVkAk67z47+NE2UigUh5oFCS0k9d/f4tWxu9nen7dZteCOwS9A4i8DEgbGAaNEdIRtK4GnOem22+dIpWMCPIBRZbbPFJ9tL6ErAFv5dKTlQz4V0dbhG+kGadq4Q0qciupHPObyFjh4TEmSnhYnCpwhwVVeXifH3Z+9cbM4/fUc9KYBvCuoY22LM/8Nbd3hRZKucEd82dGMUFgZqIcW9vHX9zPUyC70VV6iev6rloMoYKPkV9rrtltWnzyX9OcZOwsw7uT55xdx+gWabPimCgF4fDCHtA6kvGAtJmwgcfB8Pwkq4+FSNGWBRjMPUkQ7URCVZ34GLAsIVdZJ6GnC5dX38OY6uyPB04Nk+51KL2v3XsnN9EC/by5Wg0KtuDkdLU/asfPjqqEYNWJsMDDmk0MWk04PO8ayKI3IhWhNDA2nSAIw5N/HVeO8b31gQa+Fbfk0QUT67bhvjveASBOosmmbdznLOiXQ/tINGl3IF2RYQpjoactlYDM70vpo69qaQIF6/uIfc748qkFf01iKl9pMHlWQXf65X19OLRq8ism5morOUBEQR5P+Lo6+1YZJN8cDzbUWvI0X41n2RoBh2WA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:type: {}
        manager: kubectl
        operation: Update
        time: "2021-11-09T14:35:51Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
        manager: unknown
        operation: Update
        time: "2021-11-09T14:37:48Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

