apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgBZTAH+ea+9umo2T9+Og/0BoUtvFvzsbAYe9Qx2XSri7x12g2hYyre19GWLYK+zntF42r6iQyFJq/AqF8W4CtwZ3rktlBN7HsZwOK3nci4VfLGk4+XZUe+SrZmqut29yLraY60DffunCKrx1g5U3EqgSLPnaoKyC1oL8n8pJ9OVI8uT2FT43U0trwZmR+DvSub5X0W8VZr7Im3YtAhb8D3CEKo3UYUwk/Ey1WDIbv0wXlvAubVhOpjiUCtF4dBkef82oL3aibR58Fs0HfGvXqetONMPRY1xI8iPgRyMwsu2LmdcAdJfxqDhvzFDJu7i5UcaiAc17Ey6idyk7v4kIWXLACvbVvVRtknHAQQI4nq+6P9DNSinomYQH7kJdC+ByQ3Q2wOxp5usabTnyGfse575hPrlFfKp1BU3fSlFpK8wYw0LHg8BLdzrc5z4B0BzRc6Dfq/kwgO5s+Ezjj/eJJl/X0dwnLH9LYyMIk241IDIgv/OZxZfTlxY3409thYxijIGZ3+5UWrf97ZTGPHFlw3nfWdXb8bG8SyBMGHakGTSPkQm4yaZqHqiegIii7A1m9htPnPFQBBYpCmo95vOtapWZgFx7K6zL7v1TN5XxS+JeWIAuya0X4LJzZFmnGmUBTyC+75h9ErtN0Py+yMyUPCSCkQNwBVhlJsXKkU1nN1bnQTPQLehgP/V9MP7mNzwxhMLt73jS+yGWzt53dR0VEWatoRS2qMMdSi4mvMnaWDtKn5gmTEQ5thJbF0hCD+wDskax1sCpRx4TC2IA2n2ZChF3WhD/YLnUjUIsqRGTst7NHBAtK12zafSSHrI8//mnJ7u8qzhTPX21l2t4g4XA9zYs+3oEECM34C/2aESzwHdltiOYWJVznHIvw10es+6m004GIZaNARfqMUv2YBpX1TbgcX6OQLdI1NNE+Ffoax57crw6bc/pZwDjyc2nKqQJMg=
    IBM_ENTITLED_REGISTRY_USER: AgCuU5p8p7rkJ+0FfFWjCiqt5lwKYp2Xz42AWPsYSh11FVbkx2khjMCY0cOX7/JcJQtNv7iFkzs4rYkpKaKhfZBu4aM1FVod9Zm2vTgeexLYeSXVW9wJxqexoASLPxduXltDZYqUoJuqS6XVNIZHfYkHYFTmIkzO33RglbNWC5fPpBZlxRE9kbMLFUy/t5sWXDxmSeKNg8ZU4XgkJGGGNedRl6VAC63mOaX+XzP0Qr6p/xAQy8hWNFI4n6+5MZVQ7DWFezMfc0UEWWUn3lqn2n+hmU4PfmxAovwEkrtxpO9voTTUmvffs5XUq5q7GewAQvvIt1mA98zGMnJuFNdwppyMjjpcqRWXZo60xo8KCP3hkvUhjlLltnm9u5RpQTA4fOP9FHSyNSggsAfPDe7HMmzwyx/D28x4YJA0anBXt8j3Rhv6n2nVrzXuPP+r3FYqVYAs6xl/gQswEes69hGWY2mn40VNhIuSlg21VeI0Jf2uRdwOLk8d5lSqHkRi4jT+PVxoUzY5NZ7e7DPFrJZTehPgpJNwIfnlZ260gXMEry1D4BgGUmQxtoqmF6dsaI8uuYEbG6+QzfKiwOUFft8poZv5zqQlXfXbb+wO4HK9ux9c5xyQ4yg0JIvz0ckaSuc4dLu4+Wm47CSWhmxZ9Oit9L82EDoKjKZItYvpnCU2IqK8wwVMRSXG5sfpj/g5ZPhegt/UMQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

